print("Date: Sat 24 Aug")
print("Good Morning, John")
print("I recieved your mail at 10:10 a.m.")
print("")

print("Date: Sat 24 Aug")
print("Good Morning, John")
print("I recieved your mail at 10:34 a.m.")
print("")
print("Updated a message from Alice and forwarded to Bob")
print("Bob couldn't recieve the mail where he lost his mail account")
print("Requesting you to send the message on other mail..")
